// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uocgiyeeodrfqhiagiud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvY2dpeWVlb2RyZnFoaWFnaXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjUzNzksImV4cCI6MjA1OTM0MTM3OX0.MxohrjNPlSjHbckriSM6WNuKMMg6wwXy2EMbbggozY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);